#!/usr/bin/env python3
"""Generate a function signature map of the Go codebase, organized by package.
Usage: python scripts/funcmap.py [-o output.md] [--dir <project-root>]
"""
import re, os, sys, subprocess
from pathlib import Path

SKIP_DIRS = {".git", "node_modules", "vendor", ".cache", "dist", "build", ".reasonix"}

FUNC_RE = re.compile(r'^\s*(?:func\s+(?:\w+\s+)?\(?\w*(?:,\s*\w+)*\)?\s+)?func\s+(?P<name>[A-Z]\w*)\s*(?P<sig>\([^)]*\)(?:\s*\(?[^)]*\)?)?)\s*\{')
TYPE_RE = re.compile(r'^\s*type\s+(?P<name>[A-Z]\w+)\s+(?P<def>.*)')
STRUCT_RE = re.compile(r'^\s*type\s+(?P<name>[A-Z]\w+)\s+struct')
INTERFACE_RE = re.compile(r'^\s*type\s+(?P<name>[A-Z]\w+)\s+interface')

METHOD_RE = re.compile(r'^\s*func\s+\([^)]+\)\s+(?P<name>[A-Z]\w+)\s*(?P<sig>\([^)]*\)(?:\s*\(?[^)]*\)?)?)\s*\{')

def find_go_files(root):
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]
        for f in files:
            if f.endswith(".go") and not f.endswith("_test.go"):
                yield os.path.join(dirpath, f)

def extract_comment(lines, idx):
    """Get the comment block immediately before a declaration."""
    comments = []
    i = idx - 1
    while i >= 0:
        line = lines[i].strip()
        if line.startswith("//"):
            comments.insert(0, line[2:].strip())
        elif line == "":
            break
        else:
            break
        i -= 1
    return comments

def scan_file(filepath, rel_path):
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()
    
    pkg = ""
    funcs = []
    types = []
    
    for i, line in enumerate(lines):
        # Package
        m = re.match(r'^\s*package\s+(\w+)', line)
        if m:
            pkg = m.group(1)
        
        # Type declarations (exported)
        m = STRUCT_RE.match(line)
        if m:
            comment = extract_comment(lines, i)
            types.append((m.group("name"), "struct", comment, rel_path, i+1))
            continue
        
        m = INTERFACE_RE.match(line)
        if m:
            comment = extract_comment(lines, i)
            types.append((m.group("name"), "interface", comment, rel_path, i+1))
            continue
        
        m = TYPE_RE.match(line) and not STRUCT_RE.match(line) and not INTERFACE_RE.match(line)
        if m and m.group("name")[0].isupper():
            comment = extract_comment(lines, i)
            types.append((m.group("name"), m.group("def").strip()[:50], comment, rel_path, i+1))
            continue
        
        # Functions (exported, top-level)
        m = FUNC_RE.match(line)
        if m:
            comment = extract_comment(lines, i)
            funcs.append((m.group("name"), m.group("sig"), "", comment, rel_path, i+1))
            continue
        
        # Methods (exported)
        m = METHOD_RE.match(line)
        if m:
            comment = extract_comment(lines, i)
            funcs.append((m.group("name"), m.group("sig"), "method", comment, rel_path, i+1))
            continue
    
    return pkg, funcs, types

def main():
    output = "funcmap.md"
    root = os.getcwd()
    
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "-o" and i+1 < len(args):
            output = args[i+1]
            i += 2
        elif args[i] == "--dir" and i+1 < len(args):
            root = args[i+1]
            i += 2
        elif args[i] in ("-h", "--help"):
            print(f"Usage: {sys.argv[0]} [-o output.md] [--dir <project-root>]")
            sys.exit(0)
        else:
            i += 1
    
    all_funcs = {}  # pkg -> list of funcs
    all_types = {}  # pkg -> list of types
    
    for fp in find_go_files(root):
        rel = os.path.relpath(fp, root)
        pkg, funcs, types = scan_file(fp, rel)
        if pkg:
            all_funcs.setdefault(pkg, []).extend(funcs)
            all_types.setdefault(pkg, []).extend(types)
    
    lines = []
    lines.append("# Function Map\n")
    lines.append(f"Auto-generated by `scripts/funcmap.py` on {root}\n")
    lines.append(f"Exported types and functions, organized by package.\n")
    
    for pkg in sorted(all_funcs.keys() | all_types.keys()):
        lines.append(f"\n## `{pkg}`\n")
        
        types = all_types.get(pkg, [])
        if types:
            lines.append("### Types\n")
            lines.append("| Name | Kind | File | Line |")
            lines.append("|------|------|------|------|")
            for name, kind, comment, path, lineno in sorted(types, key=lambda x: x[0]):
                short_comment = comment[0][:60] if comment else ""
                lines.append(f"| `{name}` | {kind} | `{path}` | {lineno} |")
        
        funcs = all_funcs.get(pkg, [])
        if funcs:
            lines.append("\n### Functions\n")
            lines.append("| Name | Signature | Kind | File | Line |")
            lines.append("|------|-----------|------|------|------|")
            for name, sig, kind, comment, path, lineno in sorted(funcs, key=lambda x: x[0]):
                sig_short = sig[:80] + "..." if len(sig) > 80 else sig
                kind_label = "method" if kind else "func"
                short_comment = comment[0][:60] if comment else ""
                lines.append(f"| `{name}` | `{sig_short}` | {kind_label} | `{path}` | {lineno} |")
    
    output_path = os.path.join(root, output) if not os.path.isabs(output) else output
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    
    total_types = sum(len(v) for v in all_types.values())
    total_funcs = sum(len(v) for v in all_funcs.values())
    print(f"OK: {total_types} types, {total_funcs} functions in {len(all_funcs)} packages → {output}")

if __name__ == "__main__":
    main()
