// Command mcp-surface-dump exercises the REAL boot.Build path with a demo MCP
// config (15 servers × 5 tools, matching meta_capacity_test.go's scenario) and
// prints the provider-visible tool surface for both modes:
//
//  1. baseline  — REASONIX_MCP_META_TOOL unset  → per-tool mcp__<server>__<tool>
//  2. use_capability — REASONIX_MCP_META_TOOL=1  → single use_capability proxy
//
// It proves the capacity drop is real on the production boot path, not just in
// unit tests. The demo servers declare a nonexistent command so no subprocess
// actually spawns: cache-hit placeholders register from the pre-seeded schema
// cache, exactly as boot does for any previously-handshaken server. The spawn
// failure is recorded on the host (as it would be for a misconfigured server)
// but does not affect the registered surface.
//
// Usage:
//
//	go run ./cmd/mcp-surface-dump
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"reasonix/internal/boot"
	"reasonix/internal/config"
	"reasonix/internal/event"
	"reasonix/internal/plugin"
	"reasonix/internal/tool"
)

const (
	serverCount    = 15
	toolsPerServer = 5
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "mcp-surface-dump: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	ctx := context.Background()

	workspace, err := os.MkdirTemp("", "reasonix-surface-ws-")
	if err != nil {
		return fmt.Errorf("create workspace temp dir: %w", err)
	}
	defer os.RemoveAll(workspace)

	cacheDir, err := os.MkdirTemp("", "reasonix-surface-cache-")
	if err != nil {
		return fmt.Errorf("create cache temp dir: %w", err)
	}
	defer os.RemoveAll(cacheDir)
	// config.CacheDir() honors REASONIX_CACHE_HOME; point it at our temp dir so
	// pre-seeded schemas are found and nothing touches the real user cache.
	os.Setenv("REASONIX_CACHE_HOME", cacheDir)

	if err := writeDemoConfig(workspace, false); err != nil {
		return err
	}
	if err := seedDemoCaches(workspace); err != nil {
		return err
	}

	fmt.Println("=== mcp-surface-dump: real boot.Build path ===")
	fmt.Printf("workspace: %s\n", workspace)
	fmt.Printf("cache dir: %s\n", cacheDir)
	fmt.Printf("demo MCP servers: %d × %d tools = %d MCP tools configured\n", serverCount, toolsPerServer, serverCount*toolsPerServer)
	fmt.Println("enable path: [tools] meta_tool = true in reasonix.toml (config-file path, not env)")

	baseline, baselineNotices, err := buildAndDump(ctx, workspace, false /* meta-tool off */)
	if err != nil {
		return fmt.Errorf("baseline build: %w", err)
	}
	meta, metaNotices, err := buildAndDump(ctx, workspace, true /* meta-tool on */)
	if err != nil {
		return fmt.Errorf("meta-tool build: %w", err)
	}

	printComparison(baseline, meta, baselineNotices, metaNotices)
	return nil
}

// writeDemoConfig writes a reasonix.toml with an OpenAI provider (uses
// OPENAI_API_KEY from the environment) and 15 background MCP server entries.
// When metaTool is true, it adds [tools] meta_tool = true so the use_capability
// proxy is enabled via the CONFIG FILE path (not the env override) —
// this is what proves the config item works end-to-end on the real boot path.
// The provider is only needed so boot.Build resolves a model and reaches
// registerBackground — no API call is made during Build.
func writeDemoConfig(workspace string, metaTool bool) error {
	var b strings.Builder
	b.WriteString(`# Auto-generated by mcp-surface-dump. Demonstrates the run_mcp
# meta-tool capacity drop on the real boot.Build path.

default_model = "openai/gpt-4o-mini"

[[providers]]
name = "openai"
kind = "openai"
model = "gpt-4o-mini"
base_url = "https://api.openai.com/v1"
api_key_env = "OPENAI_API_KEY"

`)
	if metaTool {
		b.WriteString("[tools]\nmeta_tool = true\n\n")
	}
	for i := 0; i < serverCount; i++ {
		fmt.Fprintf(&b, "[[plugins]]\nname = \"srv%d\"\ncommand = \"nonexistent-mcp-binary-%d\"\nargs = [\"--demo\"]\n\n", i, i)
	}
	return os.WriteFile(filepath.Join(workspace, "reasonix.toml"), []byte(b.String()), 0o644)
}

// seedDemoCaches pre-seeds the schema cache for each demo server with
// toolsPerServer tools. The cache is keyed by server name + SpecFingerprint;
// we build the exact specs boot will build (via PluginSpecsForRootWithOptions)
// so the fingerprints match by construction, and LoadCachedSchema hits.
func seedDemoCaches(workspace string) error {
	cfg, err := config.LoadForRoot(workspace)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	entries := cfg.AutoStartPlugins()
	specs := boot.PluginSpecsForRootWithOptions(entries, workspace, boot.PluginSpecOptions{})
	fmt.Printf("discovered %d MCP specs (declared %d demo servers; extras come from installed packages / legacy config):\n", len(specs), serverCount)
	for _, s := range specs {
		fmt.Printf("  - %s  (command=%q)\n", s.Name, s.Command)
	}
	// Pre-seed a cache for EVERY discovered spec so all register from cache
	// (no spawn needed). Extras beyond srv0..srv14 are whatever the host
	// environment injected; giving them a 5-tool cache keeps the demo
	// comparable across modes.
	for _, spec := range specs {
		tools := make([]plugin.CachedTool, 0, toolsPerServer)
		for k := 0; k < toolsPerServer; k++ {
			tools = append(tools, plugin.CachedTool{
				Name:        fmt.Sprintf("tool%d", k),
				Description: fmt.Sprintf("Demo tool %d on %s.", k, spec.Name),
				Schema:      json.RawMessage(`{"type":"object","properties":{"msg":{"type":"string"}}}`),
			})
		}
		cs := plugin.CachedSchema{
			Version:      1,
			CacheKey:     plugin.SchemaCacheKey(spec),
			Capabilities: map[string]bool{"tools": true},
			Tools:        tools,
		}
		if err := plugin.SaveCachedSchema(spec.Name, cs); err != nil {
			return fmt.Errorf("save cache for %s: %w", spec.Name, err)
		}
	}
	return nil
}

// surface captures the provider-visible tool surface after Build.
type surface struct {
	mode             string
	totalTools       int
	mcpTopLevel      int
	hasUseCapability bool
	toolNames        []string
	schemasBytes     int
	buildErr         error
}

func buildAndDump(ctx context.Context, workspace string, metaTool bool) (surface, []string, error) {
	// Rewrite the config file with the appropriate meta_tool setting so this
	// run exercises the CONFIG FILE path, not the env override. The env var
	// is explicitly cleared to prove the config item alone drives the mode.
	os.Unsetenv("REASONIX_MCP_META_TOOL")
	if err := writeDemoConfig(workspace, metaTool); err != nil {
		return surface{mode: modeLabel(metaTool), buildErr: err}, nil, nil
	}
	// Always set DUMP so the boot.go diagnostic Notice fires and we can
	// capture it, regardless of whether meta-tool is enabled.
	os.Setenv("REASONIX_DUMP_TOOL_SURFACE", "1")

	var notices []string
	sink := event.FuncSink(func(e event.Event) {
		if e.Kind == event.Notice {
			notices = append(notices, e.Text)
		}
	})

	ctrl, err := boot.Build(ctx, boot.Options{
		WorkspaceRoot: workspace,
		RequireKey:    false,
		Sink:          sink,
		Stderr:        io.Discard,
	})
	if err != nil {
		// A build failure is still useful evidence — report it, don't exit.
		return surface{
			mode:     modeLabel(metaTool),
			buildErr: err,
		}, notices, nil
	}
	defer ctrl.Close()

	entries := ctrl.ToolContractEntries()
	s := surface{
		mode:       modeLabel(metaTool),
		totalTools: len(entries),
	}
	for _, e := range entries {
		s.toolNames = append(s.toolNames, e.Name)
		if strings.HasPrefix(e.Name, tool.MCPNamePrefix) {
			s.mcpTopLevel++
		}
		if e.Name == "use_capability" {
			s.hasUseCapability = true
		}
	}
	// Measure the serialized tools-array bytes — the real "attention" cost.
	schemas := make([]map[string]any, 0, len(entries))
	for _, e := range entries {
		schemas = append(schemas, map[string]any{
			"name":        e.Name,
			"description": e.Description,
			"parameters":  json.RawMessage(e.Schema),
		})
	}
	if b, err := json.Marshal(schemas); err == nil {
		s.schemasBytes = len(b)
	}
	return s, notices, nil
}

func modeLabel(metaTool bool) string {
	if metaTool {
		return "use_capability meta-tool"
	}
	return "per-tool mcp__ (baseline)"
}

func printComparison(baseline, meta surface, baselineNotices, metaNotices []string) {
	fmt.Println("────────────────────────────────────────────────────────────")
	fmt.Println("MODE                 tools   mcp__   use_cap   tools-array bytes")
	fmt.Println("────────────────────────────────────────────────────────────")
	printRow(baseline)
	printRow(meta)
	fmt.Println("────────────────────────────────────────────────────────────")
	if baseline.schemasBytes > 0 && meta.schemasBytes > 0 {
		drop := 100 * float64(baseline.schemasBytes-meta.schemasBytes) / float64(baseline.schemasBytes)
		fmt.Printf("bytes reduction: %d → %d  (↓ %.1f%%)\n", baseline.schemasBytes, meta.schemasBytes, drop)
	}
	if baseline.totalTools > 0 && meta.totalTools > 0 {
		drop := 100 * float64(baseline.totalTools-meta.totalTools) / float64(baseline.totalTools)
		fmt.Printf("tools reduction: %d → %d  (↓ %.1f%%)\n", baseline.totalTools, meta.totalTools, drop)
	}

	fmt.Println()
	fmt.Println("=== boot.go diagnostic Notices (baseline run) ===")
	for _, n := range baselineNotices {
		fmt.Println("  " + n)
	}
	fmt.Println()
	fmt.Println("=== boot.go diagnostic Notices (use_capability run) ===")
	for _, n := range metaNotices {
		fmt.Println("  " + n)
	}

	if meta.hasUseCapability {
		fmt.Println()
		fmt.Println("=== use_capability registered: YES (single proxy replaces all mcp__ entries) ===")
	}
	if meta.buildErr != nil {
		fmt.Printf("\n[meta-tool build error: %v]\n", meta.buildErr)
	}
	if baseline.buildErr != nil {
		fmt.Printf("\n[baseline build error: %v]\n", baseline.buildErr)
	}

	// Print the use_capability tool name list when present, so the proxy's
	// surface is visible.
	if meta.hasUseCapability {
		fmt.Println()
		fmt.Println("=== use_capability-mode tool name list ===")
		fmt.Println(strings.Join(meta.toolNames, "\n"))
	}
}

func printRow(s surface) {
	if s.buildErr != nil {
		fmt.Printf("%-22s  BUILD FAILED: %v\n", s.mode, s.buildErr)
		return
	}
	fmt.Printf("%-22s  %5d   %5d   %5v     %d\n", s.mode, s.totalTools, s.mcpTopLevel, s.hasUseCapability, s.schemasBytes)
}
