// Code generated by cmd/extension-protocol-gen; DO NOT EDIT.

package protocol

// GeneratedSchemaHash is the SHA-256 of schema.generated.json. Handshake
// comparisons use this constant; protocol tests independently recompute it
// from CanonicalSchemaBytes to reject stale generated artifacts.
const GeneratedSchemaHash = "sha256:f93ad7f8681773864a17fcb899705d7b3f7f0dce62d0940ae8ac30b3c4f46b8f"
