// Code generated by cmd/extension-protocol-gen; DO NOT EDIT.

package protocol

// GeneratedSchemaHash is the SHA-256 of schema.generated.json. Handshake
// comparisons use this constant; protocol tests independently recompute it
// from CanonicalSchemaBytes to reject stale generated artifacts.
const GeneratedSchemaHash = "sha256:aad757c8942e959b3bc2456389c481ade4bee2974aca41e278791f9ceb1ecf65"
