#!/usr/bin/env bash
# Renders the Homebrew cask for one CLI release from the digest list the
# release published, so the cask can only name archives that list vouches for.
# usage: render-brew-cask.sh <version> <tag> <SHA256SUMS>
set -euo pipefail

version="$1" tag="$2" sums="$3"
base="https://github.com/esengine/DeepSeek-Reasonix/releases/download/${tag}"

digest() {
  local d
  d="$(awk -v f="$1" '$2 == f || $2 == "*" f { print $1 }' "$sums")"
  if [[ ! "$d" =~ ^[0-9a-f]{64}$ ]]; then
    echo "render-brew-cask: no digest for $1 in $sums" >&2
    exit 1
  fi
  printf '%s' "$d"
}

darwin_arm64="$(digest reasonix-darwin-arm64.tar.gz)"
darwin_amd64="$(digest reasonix-darwin-amd64.tar.gz)"
linux_arm64="$(digest reasonix-linux-arm64.tar.gz)"
linux_amd64="$(digest reasonix-linux-amd64.tar.gz)"

cat <<EOF
# Generated by release-studio.yml from ${tag}'s SHA256SUMS. DO NOT EDIT.
cask "reasonix" do
  postflight_steps do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reasonix"]
    end
  end

  version "${version}"

  on_macos do
    on_arm do
      sha256 "${darwin_arm64}"
      url "${base}/reasonix-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "${darwin_amd64}"
      url "${base}/reasonix-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "${linux_arm64}"
      url "${base}/reasonix-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "${linux_amd64}"
      url "${base}/reasonix-linux-amd64.tar.gz"
    end
  end

  name "reasonix"
  desc "Cache-first DeepSeek coding agent for the terminal."
  homepage "https://github.com/esengine/DeepSeek-Reasonix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reasonix"
end
EOF
