// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMCPServer(arg1:main.MCPServerInput):Promise<number>;

export function AddPermissionRule(arg1:string,arg2:string):Promise<void>;

export function AddSkillPath(arg1:string):Promise<void>;

export function AnswerQuestion(arg1:string,arg2:Array<main.QuestionAnswer>):Promise<void>;

export function ApplyUpdate():Promise<void>;

export function Approve(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;

export function AttachDropped(arg1:string):Promise<main.DroppedItem>;

export function AttachmentDataURL(arg1:string):Promise<string>;

export function Balance():Promise<main.BalanceInfo>;

export function Cancel():Promise<void>;

export function Capabilities():Promise<main.CapabilitiesView>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function Checkpoints():Promise<Array<main.CheckpointMeta>>;

export function ClearMCPServerAuthentication(arg1:string):Promise<void>;

export function Commands():Promise<Array<main.CommandInfo>>;

export function Compact():Promise<void>;

export function ConnectKey(arg1:string):Promise<void>;

export function ContextUsage():Promise<main.ContextInfo>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function Effort():Promise<main.EffortInfo>;

export function Forget(arg1:string):Promise<void>;

export function Fork(arg1:number):Promise<void>;

export function History():Promise<Array<main.HistoryMessage>>;

export function Jobs():Promise<Array<main.JobView>>;

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function ListSessions():Promise<Array<main.SessionMeta>>;

export function ListWorkspaces():Promise<Array<main.WorkspaceMeta>>;

export function Memory():Promise<main.MemoryView>;

export function Meta():Promise<main.Meta>;

export function Models():Promise<Array<main.ModelInfo>>;

export function NeedsOnboarding():Promise<boolean>;

export function NewSession():Promise<void>;

export function OpenDownloadPage():Promise<void>;

export function OpenWorkspacePath(arg1:string):Promise<void>;

export function PickSkillFolder():Promise<string>;

export function PickWorkspace():Promise<string>;

export function Platform():Promise<string>;

export function PreviewSession(arg1:string):Promise<Array<main.HistoryMessage>>;

export function ReadFile(arg1:string,arg2:string):Promise<main.FilePreview>;

export function RefreshSkills():Promise<void>;

export function Remember(arg1:string,arg2:string):Promise<string>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RemovePermissionRule(arg1:string,arg2:string):Promise<void>;

export function RemoveSkillPath(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResumeSession(arg1:string):Promise<Array<main.HistoryMessage>>;

export function RetryMCPServer(arg1:string):Promise<void>;

export function RevealWorkspacePath(arg1:string):Promise<void>;

export function Rewind(arg1:number,arg2:string):Promise<void>;

export function SaveDoc(arg1:string,arg2:string):Promise<string>;

export function SavePastedFile(arg1:string,arg2:string):Promise<string>;

export function SavePastedImage(arg1:string):Promise<string>;

export function SaveProvider(arg1:main.ProviderView):Promise<void>;

export function SearchFileRefs(arg1:string):Promise<Array<main.DirEntry>>;

export function SetAgentParams(arg1:number,arg2:number,arg3:string):Promise<void>;

export function SetBypass(arg1:boolean):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetEffort(arg1:string):Promise<void>;

export function SetFileEncoding(arg1:string):Promise<void>;

export function SetMCPServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetMCPServerTier(arg1:string,arg2:string):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetNetwork(arg1:main.NetworkView):Promise<void>;

export function SetPermissionMode(arg1:string):Promise<void>;

export function SetPlanMode(arg1:boolean):Promise<void>;

export function SetPlannerModel(arg1:string):Promise<void>;

export function SetProviderKey(arg1:string,arg2:string):Promise<void>;

export function SetSandbox(arg1:string,arg2:boolean,arg3:string,arg4:Array<string>):Promise<void>;

export function Settings():Promise<main.SettingsView>;

export function SlashArgs(arg1:string):Promise<main.SlashArgsResult>;

export function Submit(arg1:string):Promise<void>;

export function SubmitDisplay(arg1:string,arg2:string):Promise<void>;

export function SummarizeFrom(arg1:number):Promise<void>;

export function SummarizeUpTo(arg1:number):Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<string>;

export function UpdateMCPServer(arg1:string,arg2:main.MCPServerInput):Promise<void>;

export function Version():Promise<string>;

export function WorkspaceChanges():Promise<main.WorkspaceChangesView>;
