// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AddPermissionRule(arg1, arg2) {
  return window['go']['main']['App']['AddPermissionRule'](arg1, arg2);
}

export function AddSkillPath(arg1) {
  return window['go']['main']['App']['AddSkillPath'](arg1);
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function Approve(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Approve'](arg1, arg2, arg3, arg4);
}

export function AttachDropped(arg1) {
  return window['go']['main']['App']['AttachDropped'](arg1);
}

export function AttachmentDataURL(arg1) {
  return window['go']['main']['App']['AttachmentDataURL'](arg1);
}

export function Balance() {
  return window['go']['main']['App']['Balance']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function Capabilities() {
  return window['go']['main']['App']['Capabilities']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function Checkpoints() {
  return window['go']['main']['App']['Checkpoints']();
}

export function ClearMCPServerAuthentication(arg1) {
  return window['go']['main']['App']['ClearMCPServerAuthentication'](arg1);
}

export function Commands() {
  return window['go']['main']['App']['Commands']();
}

export function Compact() {
  return window['go']['main']['App']['Compact']();
}

export function ConnectKey(arg1) {
  return window['go']['main']['App']['ConnectKey'](arg1);
}

export function ContextUsage() {
  return window['go']['main']['App']['ContextUsage']();
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function Effort() {
  return window['go']['main']['App']['Effort']();
}

export function Forget(arg1) {
  return window['go']['main']['App']['Forget'](arg1);
}

export function Fork(arg1) {
  return window['go']['main']['App']['Fork'](arg1);
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function Jobs() {
  return window['go']['main']['App']['Jobs']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function Memory() {
  return window['go']['main']['App']['Memory']();
}

export function Meta() {
  return window['go']['main']['App']['Meta']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function NeedsOnboarding() {
  return window['go']['main']['App']['NeedsOnboarding']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function OpenDownloadPage() {
  return window['go']['main']['App']['OpenDownloadPage']();
}

export function OpenWorkspacePath(arg1) {
  return window['go']['main']['App']['OpenWorkspacePath'](arg1);
}

export function PickSkillFolder() {
  return window['go']['main']['App']['PickSkillFolder']();
}

export function PickWorkspace() {
  return window['go']['main']['App']['PickWorkspace']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function PreviewSession(arg1) {
  return window['go']['main']['App']['PreviewSession'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function RefreshSkills() {
  return window['go']['main']['App']['RefreshSkills']();
}

export function Remember(arg1, arg2) {
  return window['go']['main']['App']['Remember'](arg1, arg2);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemovePermissionRule(arg1, arg2) {
  return window['go']['main']['App']['RemovePermissionRule'](arg1, arg2);
}

export function RemoveSkillPath(arg1) {
  return window['go']['main']['App']['RemoveSkillPath'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function RetryMCPServer(arg1) {
  return window['go']['main']['App']['RetryMCPServer'](arg1);
}

export function RevealWorkspacePath(arg1) {
  return window['go']['main']['App']['RevealWorkspacePath'](arg1);
}

export function Rewind(arg1, arg2) {
  return window['go']['main']['App']['Rewind'](arg1, arg2);
}

export function SaveDoc(arg1, arg2) {
  return window['go']['main']['App']['SaveDoc'](arg1, arg2);
}

export function SavePastedFile(arg1, arg2) {
  return window['go']['main']['App']['SavePastedFile'](arg1, arg2);
}

export function SavePastedImage(arg1) {
  return window['go']['main']['App']['SavePastedImage'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SearchFileRefs(arg1) {
  return window['go']['main']['App']['SearchFileRefs'](arg1);
}

export function SetAgentParams(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAgentParams'](arg1, arg2, arg3);
}

export function SetBypass(arg1) {
  return window['go']['main']['App']['SetBypass'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetEffort(arg1) {
  return window['go']['main']['App']['SetEffort'](arg1);
}

export function SetFileEncoding(arg1) {
  return window['go']['main']['App']['SetFileEncoding'](arg1);
}

export function SetMCPServerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetMCPServerEnabled'](arg1, arg2);
}

export function SetMCPServerTier(arg1, arg2) {
  return window['go']['main']['App']['SetMCPServerTier'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetNetwork(arg1) {
  return window['go']['main']['App']['SetNetwork'](arg1);
}

export function SetPermissionMode(arg1) {
  return window['go']['main']['App']['SetPermissionMode'](arg1);
}

export function SetPlanMode(arg1) {
  return window['go']['main']['App']['SetPlanMode'](arg1);
}

export function SetPlannerModel(arg1) {
  return window['go']['main']['App']['SetPlannerModel'](arg1);
}

export function SetProviderKey(arg1, arg2) {
  return window['go']['main']['App']['SetProviderKey'](arg1, arg2);
}

export function SetSandbox(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSandbox'](arg1, arg2, arg3, arg4);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function SlashArgs(arg1) {
  return window['go']['main']['App']['SlashArgs'](arg1);
}

export function Submit(arg1) {
  return window['go']['main']['App']['Submit'](arg1);
}

export function SubmitDisplay(arg1, arg2) {
  return window['go']['main']['App']['SubmitDisplay'](arg1, arg2);
}

export function SummarizeFrom(arg1) {
  return window['go']['main']['App']['SummarizeFrom'](arg1);
}

export function SummarizeUpTo(arg1) {
  return window['go']['main']['App']['SummarizeUpTo'](arg1);
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function UpdateMCPServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WorkspaceChanges() {
  return window['go']['main']['App']['WorkspaceChanges']();
}
