// Mock Wails runtime — browser dev (pnpm dev) only.
// Real runtime is generated by Wails at build time.

const noop = <T extends unknown[]>(..._args: T): Promise<void> => Promise.resolve();

// Window geometry
export const WindowGetPosition = () => Promise.resolve({ x: 0, y: 0 });
export const WindowGetSize = () => Promise.resolve({ w: 1240, h: 720 });
export const WindowIsMaximised = () => Promise.resolve(false);
export const WindowCenter = noop;
export const WindowSetTitle = noop;
export const WindowSetSize = noop;
export const WindowSetPosition = noop;
export const WindowMaximise = noop;
export const WindowUnmaximise = noop;
export const WindowMinimise = noop;
export const WindowUnminimise = noop;
export const WindowToggleMaximise = noop;
export const WindowClose = noop;

// Theme
export const WindowSetSystemDefaultTheme = noop;
export const WindowSetLightTheme = noop;
export const WindowSetDarkTheme = noop;
export const WindowSetBackgroundColour = (_r: number, _g: number, _b: number, _a: number) => {};

// Clipboard
export const ClipboardGetText = () => Promise.resolve("");
export const ClipboardSetText = noop;

// Events
export const EventsOn = (_name: string, _cb: (...args: unknown[]) => void) => () => {};
export const EventsOff = noop;
export const EventsEmit = noop;
export const EventsOnMultiple = noop;
export const EventsOffMultiple = noop;

// Log
export const LogPrint = (_msg: string) => {};
export const LogTrace = (_msg: string) => {};
export const LogDebug = (_msg: string) => {};
export const LogInfo = (_msg: string) => {};
export const LogWarning = (_msg: string) => {};
export const LogError = (_msg: string) => {};
export const LogFatal = (_msg: string) => {};
export const LogSetLogLevel = (_level: number) => {};

// Browser
export const BrowserOpenURL = (_url: string) => {};
export const BrowserOpenFile = (_path: string) => {};

// Environment
export const Environment = () => Promise.resolve({});

// Screen
export const ScreenGetAll = () => Promise.resolve([]);

// Menu
export const MenuSetApplicationMenu = noop;
export const MenuUpdateApplicationMenu = noop;

// Dialog
export const OpenFileDialog = () => Promise.resolve("");
export const SaveFileDialog = () => Promise.resolve("");
export const MessageDialog = () => Promise.resolve("");
