// Mock Wails runtime — browser dev (pnpm dev) only.
// Real runtime is generated by Wails at build time.

const noop = () => Promise.resolve();

export const WindowGetPosition = () => Promise.resolve({ x: 0, y: 0 });
export const WindowGetSize = () => Promise.resolve({ w: 1240, h: 720 });
export const WindowIsMaximised = () => Promise.resolve(false);
export const WindowCenter = noop;
export const WindowSetTitle = noop;
export const EventsOn = noop;
export const EventsOff = noop;
export const EventsEmit = noop;
export const LogPrint = noop;
