// Mock Wails App bindings — browser dev (pnpm dev) only.
// Real bindings are generated by Wails at build time.

const noop = () => Promise.resolve();

export const SaveWindowState = (_: unknown) => Promise.resolve();
export const GetSettings = () => Promise.resolve({});
export const SetSetting = (_: unknown) => Promise.resolve();
export const StartChat = (_: unknown) => Promise.resolve();
export const StopChat = noop;
export const SendMessage = (_: unknown) => Promise.resolve();
export const GetSessions = () => Promise.resolve([]);
export const LoadSession = (_: unknown) => Promise.resolve(null);
export const DeleteSession = (_: unknown) => Promise.resolve();
export const RenameSession = (_: unknown) => Promise.resolve();
export const GetTabs = () => Promise.resolve([]);
export const OpenTab = (_: unknown) => Promise.resolve();
export const CloseTab = (_: unknown) => Promise.resolve();
export const SwitchTab = (_: unknown) => Promise.resolve();
export const GetCommands = () => Promise.resolve([]);
export const GetSkills = () => Promise.resolve([]);
export const InstallSkill = (_: unknown) => Promise.resolve();
export const RemoveSkill = (_: unknown) => Promise.resolve();
export const GetFileTree = () => Promise.resolve([]);
export const ReadFile = (_: unknown) => Promise.resolve("");
export const WriteFile = (_: unknown) => Promise.resolve();
export const GetBalance = () => Promise.resolve({});
export const Checkpoint = (_: unknown) => Promise.resolve();
export const Rewind = (_: unknown) => Promise.resolve();
export const ExportSession = (_: unknown) => Promise.resolve("");
export const CopySession = (_: unknown) => Promise.resolve("");
