// Mock Wails App bindings — browser dev (pnpm dev) only.
// Real bindings are generated by Wails at build time.

const noop = () => Promise.resolve();

export const SaveWindowState = (args: unknown) => Promise.resolve();
export const GetSettings = () => Promise.resolve({});
export const SetSetting = (args: unknown) => Promise.resolve();
export const StartChat = (args: unknown) => Promise.resolve();
export const StopChat = noop;
export const SendMessage = (args: unknown) => Promise.resolve();
export const GetSessions = () => Promise.resolve([]);
export const LoadSession = (args: unknown) => Promise.resolve(null);
export const DeleteSession = (args: unknown) => Promise.resolve();
export const RenameSession = (args: unknown) => Promise.resolve();
export const GetTabs = () => Promise.resolve([]);
export const OpenTab = (args: unknown) => Promise.resolve();
export const CloseTab = (args: unknown) => Promise.resolve();
export const SwitchTab = (args: unknown) => Promise.resolve();
export const GetCommands = () => Promise.resolve([]);
export const GetSkills = () => Promise.resolve([]);
export const InstallSkill = (args: unknown) => Promise.resolve();
export const RemoveSkill = (args: unknown) => Promise.resolve();
export const GetFileTree = () => Promise.resolve([]);
export const ReadFile = (args: unknown) => Promise.resolve("");
export const WriteFile = (args: unknown) => Promise.resolve();
export const GetBalance = () => Promise.resolve({});
export const Checkpoint = (args: unknown) => Promise.resolve();
export const Rewind = (args: unknown) => Promise.resolve();
export const ExportSession = (args: unknown) => Promise.resolve("");
export const CopySession = (args: unknown) => Promise.resolve("");
